name: CI Pipeline

on:
  push:
    branches:
      - feat-*
  pull_requests:
    branches:
      - main

jobs:
  server:
    name: Server building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt

  client:
    name: Client Lint & Build
    runs-on: ubuntu-latest
    needs: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install client dependencies
        working-directory: frontend/
        run: npm install

      - name: Run client linter
        working-directory: frontend
        run: npm run lint

      - name: Build client
        working-directory: frontend
        run: npm run build
